name: acceso ssh

on:
    push:
        branches:
              - master

jobs:
  conexion ssh:
    runs-on: ubuntu-latest
    steps:
      - name: unirse ssh
        run: sudo apt-get update && sudo apt-get install -y sshpass
      - name: conectar ssh
        run: sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USUARIO }}@${{ secrets.IP }} "echo 'Conexión exitosa'"