name: acceso ssh

on:
    push:
        branches:
              - master

jobs:
  conexion-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: instalar ssh
        run: sudo apt-get update && sudo apt-get install -y sshpass
      - name: conectar ssh
        run: |
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USUARIO }}@${{ secrets.IP }} -p 500"
          echo 'Conexión exitosa' &&
          echo 'Hola mundo' > alvarito.txt"