name: nmap automatico

on:
  schedule:
    - cron: '0 * * * *' # Ejecutar cada minuto
  push:
    branches:
      - master

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar nmap
        run: sudo apt-get install -y nmap
      - name: Ejecutar nmap
        run: nmap nike.com
