name: nmap manual

on:
    push:
        branches:
              - master
jobs:
    hola:
        runs-on: ubuntu-latest
        steps:
            - name: instalar nmap
              run: sudo apt-get install nmap
            - name: tirar nmap
              run: nmap nike.com
